GET http://localhost:3000/admin/stats HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDA1ZGFhMWIzMTRjZmQ2MDNmNTNkMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTEzMDUyNCwiZXhwIjoxNzU5NzM1MzI0fQ.nXPpLt93pjMo33vF5wRviU2tBAHooy1Ci2RDS7qKTp8